blockExoticSubdeps: true

allowBuilds:
  '@sentry/cli': true
  cpu-features: false
  esbuild: true
  lightningcss: true
  protobufjs: false
  ssh2: false
  workerd: true
onlyBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - '@sableclient/tauri-plugin-livekit-mobile@0.4.0'
