[package]
name = "sable-push"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
sable-core = { path = "../sable-core" }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }

[lints]
workspace = true
